"""initial schema

Revision ID: 9d6803ad69e7
Revises: 
Create Date: 2026-07-21 17:23:17.520439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d6803ad69e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builder_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=False),
    sa.Column('projectName', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('initialPrompt', sa.Text(), nullable=True),
    sa.Column('selectedTemplateId', sa.String(), nullable=True),
    sa.Column('currentVersionId', sa.String(), nullable=True),
    sa.Column('ownerUserId', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('collaborators', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('createdAt', sa.Float(), nullable=True),
    sa.Column('updatedAt', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_projects_ownerUserId'), 'builder_projects', ['ownerUserId'], unique=False)
    op.create_index(op.f('ix_builder_projects_projectId'), 'builder_projects', ['projectId'], unique=True)
    op.create_table('meta',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('passwordHash', sa.String(), nullable=True),
    sa.Column('passwordSalt', sa.String(), nullable=True),
    sa.Column('emailVerified', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('tokenBalance', sa.Integer(), nullable=True),
    sa.Column('planId', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_userId'), 'users', ['userId'], unique=True)
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tokenHash', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('expiresAt', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_tokenHash'), 'auth_tokens', ['tokenHash'], unique=False)
    op.create_index(op.f('ix_auth_tokens_userId'), 'auth_tokens', ['userId'], unique=False)
    op.create_table('builder_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventId', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=True),
    sa.Column('eventType', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ts', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['builder_projects.projectId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_analytics_eventId'), 'builder_analytics', ['eventId'], unique=False)
    op.create_index(op.f('ix_builder_analytics_projectId'), 'builder_analytics', ['projectId'], unique=False)
    op.create_table('builder_edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('editId', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=True),
    sa.Column('versionId', sa.String(), nullable=True),
    sa.Column('ts', sa.Float(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('userPrompt', sa.Text(), nullable=True),
    sa.Column('actionSummary', sa.Text(), nullable=True),
    sa.Column('changeScope', sa.String(), nullable=True),
    sa.Column('targets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['builder_projects.projectId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_edits_editId'), 'builder_edits', ['editId'], unique=False)
    op.create_index(op.f('ix_builder_edits_projectId'), 'builder_edits', ['projectId'], unique=False)
    op.create_table('builder_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ts', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['builder_projects.projectId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_quality_projectId'), 'builder_quality', ['projectId'], unique=False)
    op.create_table('builder_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('releaseId', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('versionId', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('createdAt', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['builder_projects.projectId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_releases_projectId'), 'builder_releases', ['projectId'], unique=False)
    op.create_index(op.f('ix_builder_releases_releaseId'), 'builder_releases', ['releaseId'], unique=False)
    op.create_table('builder_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('templateId', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=True),
    sa.Column('galleryIndex', sa.Integer(), nullable=True),
    sa.Column('generatedAt', sa.Float(), nullable=True),
    sa.Column('doc', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['builder_projects.projectId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_templates_projectId'), 'builder_templates', ['projectId'], unique=False)
    op.create_index(op.f('ix_builder_templates_templateId'), 'builder_templates', ['templateId'], unique=False)
    op.create_table('builder_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versionId', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('trigger', sa.String(), nullable=True),
    sa.Column('createdAt', sa.Float(), nullable=True),
    sa.Column('snapshotHtml', sa.Text(), nullable=True),
    sa.Column('snapshotProfileHash', sa.String(), nullable=True),
    sa.Column('s3HtmlKey', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['builder_projects.projectId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_versions_projectId'), 'builder_versions', ['projectId'], unique=False)
    op.create_index(op.f('ix_builder_versions_versionId'), 'builder_versions', ['versionId'], unique=False)
    op.create_table('builder_working_html',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=False),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('selectedTemplateId', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['builder_projects.projectId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_working_html_projectId'), 'builder_working_html', ['projectId'], unique=True)
    op.create_table('businessProfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=False),
    sa.Column('brand', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('business', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('location', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('contact', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('design', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('skipped', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('completeness', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('updatedAt', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['builder_projects.projectId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businessProfiles_projectId'), 'businessProfiles', ['projectId'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=False),
    sa.Column('turns', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['builder_projects.projectId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_projectId'), 'conversations', ['projectId'], unique=True)
    op.create_table('project_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assetId', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=True),
    sa.Column('assetType', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('contentType', sa.String(), nullable=True),
    sa.Column('s3Key', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sizeBytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('uploadedAt', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.Float(), nullable=True),
    sa.Column('updatedAt', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['builder_projects.projectId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_assets_assetId'), 'project_assets', ['assetId'], unique=False)
    op.create_index(op.f('ix_project_assets_projectId'), 'project_assets', ['projectId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_assets_projectId'), table_name='project_assets')
    op.drop_index(op.f('ix_project_assets_assetId'), table_name='project_assets')
    op.drop_table('project_assets')
    op.drop_index(op.f('ix_conversations_projectId'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_businessProfiles_projectId'), table_name='businessProfiles')
    op.drop_table('businessProfiles')
    op.drop_index(op.f('ix_builder_working_html_projectId'), table_name='builder_working_html')
    op.drop_table('builder_working_html')
    op.drop_index(op.f('ix_builder_versions_versionId'), table_name='builder_versions')
    op.drop_index(op.f('ix_builder_versions_projectId'), table_name='builder_versions')
    op.drop_table('builder_versions')
    op.drop_index(op.f('ix_builder_templates_templateId'), table_name='builder_templates')
    op.drop_index(op.f('ix_builder_templates_projectId'), table_name='builder_templates')
    op.drop_table('builder_templates')
    op.drop_index(op.f('ix_builder_releases_releaseId'), table_name='builder_releases')
    op.drop_index(op.f('ix_builder_releases_projectId'), table_name='builder_releases')
    op.drop_table('builder_releases')
    op.drop_index(op.f('ix_builder_quality_projectId'), table_name='builder_quality')
    op.drop_table('builder_quality')
    op.drop_index(op.f('ix_builder_edits_projectId'), table_name='builder_edits')
    op.drop_index(op.f('ix_builder_edits_editId'), table_name='builder_edits')
    op.drop_table('builder_edits')
    op.drop_index(op.f('ix_builder_analytics_projectId'), table_name='builder_analytics')
    op.drop_index(op.f('ix_builder_analytics_eventId'), table_name='builder_analytics')
    op.drop_table('builder_analytics')
    op.drop_index(op.f('ix_auth_tokens_userId'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_tokenHash'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index(op.f('ix_users_userId'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('meta')
    op.drop_index(op.f('ix_builder_projects_projectId'), table_name='builder_projects')
    op.drop_index(op.f('ix_builder_projects_ownerUserId'), table_name='builder_projects')
    op.drop_table('builder_projects')
    # ### end Alembic commands ###
